### ISSUE TITLE
loading indicator only 

### ISSUE THREAD

**Issue by ramstein74** [stefanhoelzl/vue.py#1]
hello i tried your sample code but all i get is a loading indicator.
Also errors in the vue-cli deploy live
![image](https://user-images.githubusercontent.com/1210858/48943402-031a2280-ef1b-11e8-8323-49b02f10c805.png)

**Comment by stefanhoelzl** [comment]
the file which describes your vue.py app must be named `app.py` and must be located your current working directory where you run `vue-cli deploy live`

**Comment by stefanhoelzl** [comment]
i will close this!
feel free to open it again, if you still have issues.

**Comment by Ordiel** [comment]
Hi I am also having issues to get vue-cli running on windows; I could probably help with some stack traces. Here is the first one:

    $ vue-cli deploy live
    Traceback (most recent call last):
      File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "c:\python37\lib\runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "C:\Users\me\AppData\Roaming\Python\Python37\Scripts\vue-cli.exe\__main__.py", line 5, in <module>
      File "C:\Users\me\AppData\Roaming\Python\Python37\site-packages\vuecli\cli.py", line 15, in <module>
        from vuecli.provider import Static, Flask
      File "C:\Users\me\AppData\Roaming\Python\Python37\site-packages\vuecli\provider.py", line 13, in <module>
        VUE_PATH = pkg_resources.resource_filename("vue", None)
      File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 1145, in resource_filename
        self, resource_name
      File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 1395, in get_resource_filename
        return self._fn(self.module_path, resource_name)
      File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 1471, in _fn
        self._validate_resource_path(resource_name)
      File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 1517, in _validate_resource_path
        os.path.pardir in path.split(posixpath.sep) or
    AttributeError: 'NoneType' object has no attribute 'split'

This occurred while trying to run the example provided [here](https://stefanhoelzl.github.io/vue.py/docs/)
